jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      echo Add Linux dependencies
      sudo apt-get install libncurses5-dev libncursesw5-dev
      curl -L https://raw.githubusercontent.com/lvandeve/lodepng/master/lodepng.cpp --output ./UNFLoader/Include/lodepng.c
      curl -L https://raw.githubusercontent.com/lvandeve/lodepng/master/lodepng.h --output ./UNFLoader/Include/lodepng.h
      
      curl -L https://www.ftdichip.com/Drivers/D2XX/Linux/libftd2xx-x86_64-1.4.8.gz --output libftd2xx.gz
      mkdir ./libftd2xx
      tar xvzf libftd2xx.gz -C ./libftd2xx
      cd ./libftd2xx/release/
      cp WinTypes.h ftd2xx.h $BUILD_SOURCESDIRECTORY/UNFLoader/Include/
      
      echo Install FTDI driver.
      sudo cp build/lib* /usr/local/lib
      cd /usr/local/lib
      sudo ln -s libftd2xx.so.1.4.8 libftd2xx.so
      sudo chmod 0755 libftd2xx.so.1.4.8
      #cd ./build/
      #cp libftd2xx.so.1.4.8 $BUILD_SOURCESDIRECTORY/UNFLoader/Include/libftd2xx.so
      
      cd $BUILD_SOURCESDIRECTORY
      
      echo Build App
      cd ./UNFLoader/
      ls
      make -f Makefile
      #copy to artifacts directory
    displayName: 'Build Application'
    continueOnError: false

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      echo Downloading dependencies
      curl -L https://www.ftdichip.com/Drivers/CDM/CDM%20v2.12.28%20WHQL%20Certified.zip --output libftd2xx.zip
      curl -L https://github.com/wmcbrine/PDCurses/archive/3.9.zip --output PDCurses.zip
      curl -L https://raw.githubusercontent.com/lvandeve/lodepng/master/lodepng.cpp --output ./UNFLoader/Include/lodepng.c
      curl -L https://raw.githubusercontent.com/lvandeve/lodepng/master/lodepng.h --output ./UNFLoader/Include/lodepng.h
    displayName: 'Download Dependencies'
    continueOnError: false
       
       



# - job: macOS
#   pool:
#     vmImage: 'macOS-latest'
#   steps:
#   - script: |
#       echo hello from macOS
