jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      echo Add Linux dependencies
      sudo apt-get install libncurses5-dev libncursesw5-dev
      curl -L https://raw.githubusercontent.com/lvandeve/lodepng/master/lodepng.cpp --output ./UNFLoader/Include/lodepng.c
      curl -L https://raw.githubusercontent.com/lvandeve/lodepng/master/lodepng.h --output ./UNFLoader/Include/lodepng.h
      
      curl -L https://www.ftdichip.com/Drivers/D2XX/Linux/libftd2xx-x86_64-1.4.8.gz --output libftd2xx.gz
      gzip -d libftd2xx.gz
      echo TODO: copy libftdi files
      cd ./libftd2xx
      ls
      cd ..
      
      echo Build App
      cd ./UNFLoader/
      ls
      make -f Makefile
      #copy to artifacts directory

# - job: Windows
#   pool:
#     vmImage: 'windows-latest'
#   - script: |
#       echo Building



# - job: macOS
#   pool:
#     vmImage: 'macOS-latest'
#   steps:
#   - script: |
#       echo hello from macOS
